//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartLib.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        public int Id { get; set; }
        
        public string Title { get; set; }
        public int CategoryId { get; set; }
        [DataType(DataType.MultilineText)]
        public string Brief { get; set; }
        public string Publisher { get; set; }
        public string PubYear { get; set; }
        public string Author { get; set; }
        public string BookCode { get; set; }
        public Nullable<int> QtyInStock { get; set; }
        public Nullable<byte> ViewNo { get; set; }
        public Nullable<byte> BorrowNo { get; set; }
        public Nullable<int> CopyNo { get; set; }
        public string CoverImg { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
