//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartLib.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Book
    {
        public int Id { get; set; }
        [Display(Name = "Tên sách")]
        [Required(ErrorMessage = "Tên sách không được để trống.")]
        public string Title { get; set; }
        [Display(Name = "Loại sách")]
        [Required(ErrorMessage = "Loại sách không được để trống.")]
        public int CategoryId { get; set; }
        [Display(Name = "Tóm tắt")]
        [Required(ErrorMessage = "Tóm tắt không được để trống.")]
        public string Brief { get; set; }
        [Display(Name = "Nhà xuất bản")]
        [Required(ErrorMessage = "Nhà xuất bản không được để trống.")]
        public string Publisher { get; set; }
        [Display(Name = "Năm xuất bản")]
        [Required(ErrorMessage = "Năm xuất bản không được để trống.")]
        public string PubYear { get; set; }
        [Display(Name = "Tác giả")]
        [Required(ErrorMessage = "Tác giả không được để trống.")]
        public string Author { get; set; }
        [Display(Name = "Mã sách")]
        [Required(ErrorMessage = "Mã sách không được để trống.")]
        public string BookCode { get; set; }
        [Display(Name = "Số cuốn khả dụng")]
        public Nullable<int> QtyInStock { get; set; }
        [Display(Name = "Số lượt xem")]
        public Nullable<int> ViewNo { get; set; }
        [Display(Name = "Số cuốn đã mượn")]
        public Nullable<int> BorrowNo { get; set; }
        [Display(Name = "Số cuốn")]
        public Nullable<int> CopyNo { get; set; }
        [Display(Name = "Ảnh bìa")]
        public string CoverImg { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
