//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Registrations = new HashSet<Registration>();
            this.Borrows = new HashSet<Borrow>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int CategoryId { get; set; }
        public string Brief { get; set; }
        public string Publisher { get; set; }
        public string PubYear { get; set; }
        public string Author { get; set; }
        public string BookCode { get; set; }
        public Nullable<int> QtyInStock { get; set; }
        public Nullable<int> ViewNo { get; set; }
        public Nullable<int> BorrowNo { get; set; }
        public Nullable<int> CopyNo { get; set; }
        public string CoverImg { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration> Registrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Borrow> Borrows { get; set; }
    }
}
